### PR TITLE
Now using action buttons

### LINKED ISSUE #1: Initialize poll with pre-defined reactions
Send the message with pre-added reactions so people don't need to search for a reaction to vote.

### LINKED ISSUE #2: Prevent invalid reactions
the app should prevent reactions other than the questions of the poll

### LINKED ISSUE #6: update docs so its clear that this is not actually a poll as one would expect.
https://gist.github.com/sampaiodiego/db4b60717e7ac0051024dde23c6a902e#gistcomment-1808702

Just to help folks understand how this is intended to work because it is not at all clear. In the italics in the example output you will see the actual instructions: "Please vote using reactions". This script does nothing but format a polling question in rocket.chat, it does not manage the poll results, nor does it provide an ability to vote. The users are expected to use the reactions capabilities in rocket.chat for that message to indicate their vote.

### PR DESCRIPTION
**Pull request by igor9silva**
Closes #1
Closes #2
Closes #6

### Full refactor, including:
- swap reactions for action buttons
- sends a new message containing the current results after each vote
- blocks users from voting twice
- supports multiple polls at the same time

#### Note:
I've used the **Persistence API** methods keyed by association (and not the generated ID) because updating by ID isn't implemented yet, as per: https://github.com/RocketChat/Rocket.Chat/blob/3e33c5c638f83e12f8cd08d2bc78f7886fa029de/packages/rocketchat-apps/server/bridges/persistence.js

#### Note 2:
I haven't found any docs on that, so I'm not sure if setting it's `model` property to `RocketChatAssociationModel.MISC` is the correct approach.

### CODE REVIEW

**Comment by igor9silva** [comment]
@sampaiodiego I've took the freedom to update the required engine version and to update the version into 1.0.0.

**Comment by sampaiodiego** [comment]
I would like to thank you again @igor9silva .. the PR is amazing..

It's just a bit off from what I thought initially.. I did a few modification to get this result, wdyt?

image

(unfortunate there is now to render emojis on action buttons :roll_eyes: I might send a PR to Rocket.Chat to fix that :grimacing: )

so when voting, instead of sending a new message I would like to update the original message with current votes for each option.. I could not get updating the message working yet, but I'll give it a try again tomorrow.

**Comment by igor9silva** [comment]
That really seems better, @sampaiodiego!

I haven't really tried updating the original message because since there is not an "end poll" feature yet, I thought I'd be a little bit odd. I might be working on it as soon as I'm able to.

**Comment by sampaiodiego** [comment]
cool.. I have the code in place already.. but I have found a bug which prevents from updating the message.. I'm thinking on fix it on Rocket.Chat side first.. I'll push my changes to this PR in the mean time :wink:

**Comment by sampaiodiego** [comment]
Alright! I've sent my changes and this is how it looks now:
image

Just waiting https://github.com/RocketChat/Rocket.Chat/pull/13294 to land to merge this and cut a release :tada:

**Comment by geekgonecrazy** [comment]
o.O this is pretty sweet!

**Pull request merged**
